source 'https://rubygems.org'

gem 'coffee-rails', '~> 4.0.0'
gem 'jbuilder', '~> 2.0'
gem 'jquery-rails'
gem 'pg'
gem 'rails', '~>4.2.0'

gem 'sdoc', '~> 0.4.0',          group: :doc
gem 'turbolinks'
gem 'uglifier', '>= 1.3.0'

gem 'bootstrap-sass', '~> 3.3.6'
gem 'sass-rails', '>= 3.2'
gem 'bcrypt'

group :development do
  gem 'letter_opener'
  gem 'better_errors'
  gem 'binding_of_caller'
  gem 'spring'
  gem 'pry-rails'
  gem 'faker'
end
