# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3398a8bfca23466d8cca232b85f60fe7fc636f64156bd49fa69d1484b67709325edc64bbb36b3749f6427c3217554770114c7784b2804dab6b653f3559562328

test:
  secret_key_base: 26699298baf25394367023e94f8cc7b71904223fa3e4ea71432e39ceafdcb840481d0acb3e81f726fb8cc1f3f9ad9eef0ead41142990620ee6ccccf2c7e5a40d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
